apiVersion: v1
data:
  {{ if eq .Values.pluginToUse "isecl-plugin" }}
  config.yaml: |-
    {{- toYaml .Values.iseclPlugin.configFromYaml | nindent 4 }}
  {{- else if eq .Values.pluginToUse "kmra-plugin" }}
    {{- toYaml .Values.kmraPlugin.configMap.config | nindent 2 }}
  {{- else }}
    {{- toYaml .Values.nullPlugin.configMap.config | nindent 2 }}
  {{- end }}
kind: ConfigMap
metadata:
  {{- if eq .Values.pluginToUse "kmra-plugin" }}
  name: {{ .Values.kmraPlugin.configMap.name }}
  {{- else if eq .Values.pluginToUse "isecl-plugin" }}
  name: {{ .Values.iseclPlugin.configMap.name }}
  {{- else }}
  name: {{ .Values.nullPlugin.configMap.name }}
  {{- end }}
  namespace: {{ .Values.nameSpace }}
---
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: 55c5974b.tac.intel.com
kind: ConfigMap
metadata:
  name: tac-manager-config
  namespace: {{ .Values.nameSpace }}
