apiVersion: v1
data:
  ca.crt: {{ default "" .Values.secrets.caCrt | quote }}
  client.crt: {{ default "" .Values.secrets.clientCrt | quote }}
  client.key: {{ default "" .Values.secrets.clientKey | quote }}
kind: Secret
metadata:
  {{- if eq .Values.pluginToUse "kmra-plugin" }}
  name: {{ .Values.kmraPlugin.secretName }}
  {{- else if eq .Values.pluginToUse "isecl-plugin" }}
  name: {{ .Values.iseclPlugin.secretName }}
  {{- else }}
  name: {{ .Values.nullPlugin.secretName }}
  {{- end }}
  namespace: {{ .Values.nameSpace }}
