apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: {{ .Values.service.name }}
  namespace: {{ .Values.nameSpace }}
spec:
  ports:
  - name: https
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    control-plane: controller-manager
