nameSpace: attestation-controller

# Name of the plugin configuration you want to use
# [null, kmra, isecl] leave empty to default to the null-plugin
pluginToUse: kmra-plugin


image:
  hub: intel
  name: trusted-attestation-controller
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"


secrets:
  caCrt:
  clientCrt:
  clientKey:


deployment:
  replicaCount: 1

  pullPolicy: Always

  port: 8081

  livenessProbe:
    initialDelaySeconds: 15
    periodSeconds: 20
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
  
  limits:
    cpu: 200m
    memory: 100Mi

  requests:
    cpu: 100m
    memory: 20Mi


service:
  name: tac-metrics-service

  port: 8443
  targetPort: https

serviceAccount:
  name: tac-svcact


volumes:
  - emptyDir: {}
    name: plugin-socket-dir
  - emptyDir: {}
    name: registry-socket-dir

volumeMounts:
  - name: plugin-socket-dir
    mountPath: /plugins
  - name: registry-socket-dir
    mountPath: /registration


pluginResources: # Resources used by the plugins
  limits:
    cpu: 500m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 20Mi


nullPlugin: # Configuration for null-plugin
  name: null-plugin

  args:
    - --plugin-name=null
    - --plugin-socket-path=/plugins/null.sock

  command:
    - /null-plugin

  configMap:
    name: null-config
    config:
      KEY_SERVER: ""
  
  secretName: null-secrets


kmraPlugin: # Configuration for kmra-plugin
  name: kmra-plugin

  pluginNameArg:
    - --plugin-name=kmra

  args:
    - --plugin-name=kmra
    - --plugin-socket-path=/plugins/kmra.sock

  command:
    - /kmra-plugin

  configMap:
    name: kmra-config
    config:
      KEY_SERVER: ""

  secretName: kmra-secrets

  volumes:
    - name: kmra-secrets
      secret:
        secretName: kmra-secrets
  
  volumeMounts:
    - name: kmra-secrets
      mountPath: /certs/
      readOnly: true


iseclPlugin: # Configuration for isecl-plugin
  name: isecl-plugin

  pluginNameArg:
    - --plugin-name=isecl
  
  args:
    - --plugin-name=isecl
    - --plugin-socket-path=/plugins/isecl.sock
  
  command:
    - /isecl-plugin
  
  configMap:
    name: tac-config
  
  secretName: kbs-secrets

  volumes:
    - name: tac-config
      configMap:
        name: tac-config
    - name: kmip-secrets
      secret:
        secretName: kmip-secrets
    - name: kmip-secrets
      secret:
        secretName: kmip-secrets

  volumeMounts:
    - name: tac-config
      mountPath: /etc/tac
    - name: kmip-secrets
      mountPath: /etc/tac/kmip-certs
      readOnly: true
    - name: kbs-secrets
      mountPath: /etc/tac/kbs-certs
      readOnly: true

  configFromYaml:
    #
    # iSecL plugin client configuration in YAML format
    #
    kbs:
      # KBS server hostname/ip-address
      host:
      # Client Certificate and Privatekey paths
      # Make sure that the KBS client secrets are mounted
      # at this path: /etc/tac/kbs-certs
      caCert: "/etc/tac/kbs-certs/ca.crt"
      clientKey: "/etc/tac/kbs-certs/client.key"
      clientCert: "/etc/tac/kbs-certs/client.crt"
      # Bearer token to access KBS API
      token:
    # SGX Quote Verification Service
    sqvs:
      host:
    kmip:
      # Server IP address
      ip:
      # Server hostname
      hostname:
      # Server port number defaults to 5696
      port:
      # base64 encoded username and password to access the server
      username: ""
      password: ""
      # Client Certificate and Privatekey paths
      # Make sure that the KMIP client secrets are mounted
      # at this path: /etc/tac/kmip-certs
      caCert: "/etc/tac/kmip-certs/ca.crt"
      clientKey: "/etc/tac/kmip-certs/client.key"
      clientCert: "/etc/tac/kmip-certs/client.crt"
